[build]
  base = "/"
  publish = "build"
  command = "npm run build"

[[redirects]]
from = "/*"
to = "/index.html"    # ✅ 메뉴탭 포함된 index.html로 변경
status = 200

[[redirects]]
from = "/factory.html"
to = "/factory.html"
status = 200

[[redirects]]
from = "/partner.html"
to = "/partner.html"
status = 200

[[redirects]]
from = "/internal.html"
to = "/internal.html"
status = 200

# 출입 인원 그래프
[[redirects]]
  from = "/partner_entry_chart.html"
  to = "/partner_entry_chart.html"
  status = 200

# 불량 분석 차트
[[redirects]]
  from = "/pie_defect.html"
  to = "/pie_defect.html"
  status = 200

# 불량 지표
[[redirects]]
  from = "/defect_cards.html"
  to = "/defect_cards.html"
  status = 200

[[redirects]]
  from = "/partner_kpi.html"
  to = "/partner_kpi.html"
  status = 200  
