[build]
  base = "/"
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/factory/*"
  to = "https://gst-factory.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
