[build]
  base = "/"
  publish = "."
  command = "npm run build"

[[redirects]]
  from = "/factory"
  to = "/factory/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
