[build]
  base = "/"
  publish = "."
  command = "npm run build"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/partner.html"
  to = "/partner.html"
  status = 200

[[redirects]]
  from = "/internal.html"
  to = "/internal.html"
  status = 200
