[build]
  base = "/"
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/"
  to = "/factory.html"
  status = 200

[[redirects]]
  from = "/factory.html"
  to = "/factory.html"
  status = 200

[[redirects]]
  from = "/partner.html"
  to = "/partner.html"
  status = 200

[[redirects]]
  from = "/internal.html"
  to = "/internal.html"
  status = 200
